package com.lexpilot.conversation.entity;

import jakarta.persistence.*;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * JPA entity mapping the {@code conversations} table.
 * Represents a single chat session containing an ordered list of messages.
 */
@Entity
@Table(name = "conversations")
public class ConversationEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(columnDefinition = "UUID")
    private UUID id;

    @Column(name = "created_at", nullable = false, updatable = false)
    private OffsetDateTime createdAt = OffsetDateTime.now();

    @Column(name = "updated_at", nullable = false)
    private OffsetDateTime updatedAt = OffsetDateTime.now();

    @OneToMany(mappedBy = "conversation", cascade = CascadeType.ALL, orphanRemoval = true)
    @OrderBy("id ASC")
    private List<ConversationMessageEntity> messages = new ArrayList<>();

    protected ConversationEntity() {
        // JPA requires a no-arg constructor
    }

    /**
     * Create a new conversation. The ID is auto-generated by the database.
     */
    public static ConversationEntity create() {
        return new ConversationEntity();
    }

    // ---- Getters & setters ----

    public UUID getId() {
        return id;
    }

    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(OffsetDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public List<ConversationMessageEntity> getMessages() {
        return messages;
    }

    /**
     * Touch the updated_at timestamp to reflect new activity.
     */
    public void touch() {
        this.updatedAt = OffsetDateTime.now();
    }
}
